### ISSUE TITLE
NoSuchMethodException org.jboss.resteasy.client.exception.mapper.ApacheHttpClient4ExceptionMapper.mapHttpException

### ISSUE THREAD

**Issue by tdzierza** [mmatloka/arquillian-gradle-sample#3]
Firtsly i downloaded and run arquillian-gradle-sample, and its working [OK]

Next i moved build.gradle to my war subproject (I have two subprojects jar and war closed in ear). 

And i get:

Caused by: java.lang.Exception: {"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./e5aeeef4-e86c-485e-a0ad-7f5a5235d014" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./e5aeeef4-e86c-485e-a0ad-7f5a5235d014: com.google.common.util.concurrent.ExecutionError: java.lang.ExceptionInInitializerError
    Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.ExceptionInInitializerError
    Caused by: java.lang.ExceptionInInitializerError
    Caused by: org.jboss.weld.exceptions.WeldException: WELD-000625: Unable to locate method: org.jboss.resteasy.client.exception.mapper.ApacheHttpClient4ExceptionMapper.mapHttpException(org.apache.http.HttpException)
    Caused by: java.lang.NoSuchMethodException: org.jboss.resteasy.client.exception.mapper.ApacheHttpClient4ExceptionMapper.mapHttpException(org.apache.http.HttpException)"}}
	at org.jboss.as.controller.client.helpers.standalone.impl.ServerDeploymentPlanResultFuture.getActionResult(ServerDeploymentPlanResultFuture.java:134)
	at org.jboss.as.controller.client.helpers.standalone.impl.ServerDeploymentPlanResultFuture.getResultFromNode(ServerDeploymentPlanResultFuture.java:123)
	at org.jboss.as.controller.client.helpers.standalone.impl.ServerDeploymentPlanResultFuture.get(ServerDeploymentPlanResultFuture.java:85)
	at org.jboss.as.controller.client.helpers.standalone.impl.ServerDeploymentPlanResultFuture.get(ServerDeploymentPlanResultFuture.java:42)
	at org.jboss.as.controller.client.helpers.standalone.ServerDeploymentHelper.deploy(ServerDeploymentHelper.java:55)
	at org.jboss.as.arquillian.container.ArchiveDeployer.deployInternal(ArchiveDeployer.java:77)

I tought that maybe it is something wrong with jar dependencies because war is the same. But inside jar there is nothing with rest.

When i switch to manualy shrink addClasses its working.

**Comment by mmatloka** [comment]
Hi @tdzierza , what WildFly version are you using?

**Comment by tdzierza** [comment]
Firstly Wildfly 9.0.1.Final , and then 8.2.1.Final (with the same effect)

**Comment by mmatloka** [comment]
@tdzierza I am trying to replicate this issue, however, can you provide mini-project where this issue appears (or point to your project repo if its open-source) :) ? This would help a lot :)

**Comment by tdzierza** [comment]
This is non open source project. I can share with you because this is very begining of this project. I need your email address.

**Comment by mmatloka** [comment]
@tdzierza ok, I won't paste it directly here, but it's available here https://github.com/shrinkwrap/resolver/blob/master/api-gradle-embedded-archive/src/main/java/org/jboss/shrinkwrap/api/gradle/archive/importer/embedded/EmbeddedGradleImporter.java#L26 :) .

**Comment by mmatloka** [comment]
@tdzierza from initial debugging it looks like there is a problem with dependencies of your project. The most conflicting part is `compile group: 'org.wildfly', name: 'wildfly-ejb3', version: '9.0.0.Final'` which includes reasteasy (and its dependencies) - and this is what creates this described issue (different lib version results in NoSuchMethodException).

Apart from that you have e.g. included `org.jboss.spec:jboss-javaee-6.0` which is java ee 6, but `wildfly-ejb` is already a java ee 7.

**Comment by tdzierza** [comment]
Yeah, that was the reason. I feel like amateur :)
Thanks a lot for your time.
